server:
  port: 8083

spring:
  application:
    name: adjustment-consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/settlement
    username: settlement
    password: settlement
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: adjustment-consumer-v1
      auto-offset-reset: earliest

app:
  kafka:
    adjustment-topic: settlement.adjustment.v1
