server:
  port: 8081

spring:
  application:
    name: settlement-batch
  datasource:
    url: jdbc:postgresql://localhost:5432/settlement
    username: settlement
    password: settlement
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  kafka:
    bootstrap-servers: localhost:19092
